version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.12.0-ce-win47
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t chrome .
